### ISSUE TITLE
Android repo gone?

### ISSUE THREAD

**Issue by IzzySoft** [bircni/ParkenUlm#1]
Looks like https://github.com/bircni/ParkenUlmAndroid is gone, which is used by F-Droid to build your app. Did you accidentally make it private, or has it moved elsewhere?

**Comment by IzzySoft** [comment]
@bircni any hint?

**Comment by IzzySoft** [comment]
@bircni you're still there?

**Comment by IzzySoft** [comment]
Anybody home? It's 4 months now. A simple reply possible, @bircni – or do we leave those using your app standing in the rain?

**Comment by bircni** [comment]
Hi @IzzySoft  sorry for this late late late response !

The repository is live again!

**Comment by IzzySoft** [comment]
Great, thanks! :star_struck: Re-activated auto-updates in my repo again (effective immediately), and [also at F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13912) (effective once merged, with the next build cycle then).

Just wondering if you want to share the reason behind its "temporary disappearance"?
