### ISSUE TITLE
App on IzzyOnDroid

### ISSUE THREAD

**Issue by IzzySoft** [bircni/ParkenUlm#12]
Any plans to provide the APK outside of Google's walled garden – e.g. by attaching it here to [releases](https://github.com/bircni/ParkenUlm/releases) – so people without access to PlayStore can use it, too?

Further, what license is the app covered by? I couldn't find that mentioned here in the repo. If you didn't decide yet, [this page](https://spdx.org/licenses/) might prove helpful. Make sure to pick one approved by OSI/EFF :wink:

Thanks in advance!

**Comment by bircni** [comment]
I can provide the APK in releases if you want 😊

What license do you recommend?

You can also open a PR if you have any changes to suggest

**Comment by IzzySoft** [comment]
> I can provided the APK in [releases](https://github.com/bircni/ParkenUlm/releases) :blush:

Cool, thanks!

> What license do you recommend?

Depends on what you like. To focus on some of the most used, you've got the choice on a scale reaching from WTFPL ("do WTF you like with it"– kinda "public domain") via Apache, MIT & BSD-2/3-Clause in the middle, up to more copy-left style ones like GPL2/3 or AGPL. There are plenty more, but one cannot know them all I guess – nor does one need to, as long one has identified a license fitting the project. All the ones I've just mentioned are fine for F/LOSS projects.

> You can also open a PR if you have any changes to suggest

I'm aware of that, and that's one of the reasons I ask for the license used. I'm not an Android dev but still have things to contribute (more on that later), but I'll prefer to do so only if it's F/LOSS :wink:

**Comment by bircni** [comment]
added a LICENSE
Feel free to contact me and help me improving my project

**Comment by IzzySoft** [comment]
Wonderful! Just added it to my repo, will [show up here](https://apt.izzysoft.de/fdroid/index/apk/development.parkenulm) in less than 2h from now.

You might wonder about the `NonFreeNet` flag: I couldn't find any license information at the website the data come from, so I had to apply that "marker". If you can point me where it shows that, and it's under a free license, I'll remove that marker ASAP. Seeing it's a GmbH and not seeing a license, the closest assumption is it's provided free-of-charge but not necessarily under a free license (se, same issue as above).

If you like what you see in my repo, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your Readme (there's one that matches fine to the Google badge).

So as I suggested it above: would you be interested in a PR with the metadata you see in my repo? Then I'd prepare one (including some hints on their maintenance). Note that I removed the frames from around the screenshots, with small screens in mind (the frames add no real value, but details would be harder to spot on small screens).

Oh, and congrats to the magic number: Your app is numer 1.000 in my repo now :partying_face:

**Comment by bircni** [comment]
@IzzySoft 

> You might wonder about the `NonFreeNet` flag: I couldn't find any license information at the website the data come from, so I had to apply that "marker". If you can point me where it shows that, and it's under a free license, I'll remove that marker ASAP. Seeing it's a GmbH and not seeing a license, the closest assumption is it's provided free-of-charge but not necessarily under a free license (se, same issue as above).

I asked the provider if it's ok to use this data and they allowed it.

> If you like what you see in my repo, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your Readme (there's one that matches fine to the Google badge).

It will be added in the next commits

> So as I suggested it above: would you be interested in a PR with the metadata you see in my repo? Then I'd prepare one (including some hints on their maintenance). Note that I removed the frames from around the screenshots, with small screens in mind (the frames add no real value, but details would be harder to spot on small screens).

Yes PR's are always welcome so feel free to do so if you have time and want to - I will review it then.

> Oh, and congrats to the magic number: Your app is numer 1.000 in my repo now :partying_face:

Wow very thank you! :partying_face:

**Comment by IzzySoft** [comment]
> I asked the provider if it's ok to use this data and they allowed it.

Yes, I assumed that much (you even placed credits in the Readme). But did they attach a license to it? If they permitted *you* that's an allowance all right, but just for *you* – a free license allows it for all.

Oh, and I unfortunately only noticed after my last comment that there's also GMaps inside (causing some other non-free dependencies), so I had to add the `NonFreeDep` as well. Amended the app description accordingly so it's clear where the two come from. And while for an unaccustomed eye those warnings might look a bit scary, most regular F-Droid users handle them fine. In case of your app, it would be good if you could replace GMaps by something from OSM to get rid of that "tainting". Getting the data owner to admit a free license would be icing on the cake, NonFreeNet is not that scary (some famous apps like Newpipe carry it as well). Of course I'd not discourage you from trying, mind me :rofl:

> It will be added in the next commits

Wonderful! Looking forward to that!

> Yes PR's are always welcome

Then let me prepare one :smiley:

**Comment by bircni** [comment]
@IzzySoft 
The GMaps will be removed later ig xD
Just deployed a new release with small improvements and added your stuff to the `README`

**Comment by IzzySoft** [comment]
Aww, that looks cool, thanks! PR is ready for your review. Should questions come up, I'll try to answer them as good as I can.

**Comment by bircni** [comment]
Finished this Issue and created a new one #16

**Comment by bircni** [comment]
> Oh, and I unfortunately only noticed after my last comment that there's also GMaps inside (causing some other non-free dependencies), so I had to add the NonFreeDep as well.

@IzzySoft this got removed now 😄

**Comment by IzzySoft** [comment]
Indeed, very good! Strange that my updater didn't report that. Ah, right: NonFreeNet & NonFreeDep are not only told by libraries – so they're reported when detected in a dependency so I add them, but not reported to remove when no lib triggers it anymore.

OK, removed NonFreeDep (will be reflected with the next sync). As for NonFreeNet: I guess that has to remain – or is the server-side fully F/LOSS, or can be replaced by the users' own choices?

**Comment by bircni** [comment]
@IzzySoft 
Looks like the NonFreeNet wont be removed at any time so thats it
