### ISSUE TITLE
Update App-Version on IzzyOnDroid

### ISSUE THREAD

**Issue by bircni** [bircni/ParkenUlm#16]
When and how is the available version of the app being updated on IzzyOnDroid?
@IzzyOnDroid

**Comment by IzzySoft** [comment]
Within 24h of your creating a new release and attaching the APK to it (provided you kept the naming patterns, else my updater might be confused :wink:).

**Comment by bircni** [comment]
Thanks!

**Comment by IzzySoft** [comment]
Gladly!
